name: Cardinal Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install & build pskwebcomponents
      run: |
        cd ..
        git clone https://github.com/PrivateSky/pskwebcomponents.git
        cd pskwebcomponents
        npm ci
        echo $(npm run build)
    - name: npm install
      run: |
        npm ci
        gulp build
    - name: push to gh-pages
      run: |
        remote_repo="https://${GITHUB_ACTOR}:${secrets.GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push "${remote_repo}" HEAD:gh-pages --follow-tags;   
      env:
        CI: true
