name: Cardinal Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install & build pskwebcomponents
      if: failure()
      run: |
        cd ..
        git clone https://github.com/PrivateSky/pskwebcomponents.git
        cd pskwebcomponents
        npm ci
        npm run build
    - name: npm install
      run: |
        npm ci
        gulp build
      env:
        CI: true
